import type { Facility, OutreachLog, RouteStop } from "./types";

export const initialFacilities: Facility[] = [
  {
    id: "memorial-snf",
    name: "Memorial SNF",
    address: "12620 Memorial Dr, Houston, TX",
    city: "Memorial",
    lat: 29.7728,
    lng: -95.5585,
    facilityType: "SNF",
    groupTag: "Independent",
    contacts: [
      {
        id: "c-memorial-amy",
        name: "Amy",
        role: "SLP",
        phone: "555-0102",
        preferredMethod: "text",
        primary: true,
      },
    ],
    lastContacted: "2026-06-07",
    lastVisited: "2026-05-30",
    sameDayFriendly: "sometimes",
    typicalVolume: "medium",
    notes: "Front desk is fast if the SLP knows we are coming.",
  },
  {
    id: "park-manor-westchase",
    name: "Park Manor Westchase",
    address: "11910 Richmond Ave, Houston, TX",
    city: "Westchase",
    lat: 29.7299,
    lng: -95.5887,
    facilityType: "SNF",
    groupTag: "Park Manor",
    contacts: [
      {
        id: "c-westchase-maria",
        name: "Maria",
        role: "SLP",
        phone: "555-0144",
        preferredMethod: "text",
        primary: true,
      },
      {
        id: "c-westchase-ken",
        name: "Ken",
        role: "Rehab Manager",
        phone: "555-0160",
        preferredMethod: "call",
      },
    ],
    lastContacted: "2026-06-21",
    lastVisited: "2026-06-12",
    sameDayFriendly: "yes",
    typicalVolume: "high",
    notes: "Usually has clear diet orders ready by late morning.",
  },
  {
    id: "lakeside-rehab",
    name: "Lakeside Rehab",
    address: "9440 Bellaire Blvd, Houston, TX",
    city: "Sharpstown",
    lat: 29.7066,
    lng: -95.5492,
    facilityType: "Rehab Hospital",
    groupTag: "Independent",
    contacts: [
      {
        id: "c-lakeside-nora",
        name: "Nora",
        role: "SLP Lead",
        phone: "555-0119",
        preferredMethod: "text",
        primary: true,
      },
    ],
    lastContacted: "2026-06-19",
    lastVisited: "2026-06-19",
    sameDayFriendly: "sometimes",
    typicalVolume: "medium",
    notes: "Ask for schedule constraints before promising a same-day slot.",
  },
  {
    id: "encompass-westchase",
    name: "Encompass Rehab Westchase",
    address: "12005 Richmond Ave, Houston, TX",
    city: "Westchase",
    lat: 29.7318,
    lng: -95.5935,
    facilityType: "Rehab Hospital",
    groupTag: "Encompass",
    contacts: [
      {
        id: "c-encompass-lisa",
        name: "Lisa",
        role: "SLP Lead",
        phone: "555-0188",
        email: "lisa@example.test",
        preferredMethod: "text",
        primary: true,
      },
    ],
    lastContacted: "2026-06-10",
    lastVisited: "2026-05-23",
    sameDayFriendly: "yes",
    typicalVolume: "high",
    notes: "Strong add-on candidate when already in Westchase. Lisa prefers short texts before 9 AM.",
    parkingNotes: "Park near rehab entrance on west side.",
  },
  {
    id: "westchase-nursing",
    name: "Westchase Nursing and Rehab",
    address: "8820 Westpark Dr, Houston, TX",
    city: "Westchase",
    lat: 29.7221,
    lng: -95.5259,
    facilityType: "SNF",
    groupTag: "Gulf Coast Care",
    contacts: [
      {
        id: "c-westchase-rina",
        name: "Rina",
        role: "SLP",
        phone: "555-0127",
        preferredMethod: "call",
        primary: true,
      },
    ],
    lastContacted: "2026-05-31",
    lastVisited: "2026-05-07",
    sameDayFriendly: "sometimes",
    typicalVolume: "medium",
    notes: "Often needs a reminder that add-ons must be facility-level, no PHI over text.",
  },
  {
    id: "oakbend-rehab",
    name: "Oakbend Rehab",
    address: "22003 Southwest Fwy, Richmond, TX",
    city: "Richmond",
    lat: 29.5557,
    lng: -95.7181,
    facilityType: "Rehab Hospital",
    groupTag: "Oakbend",
    contacts: [
      {
        id: "c-oakbend-sam",
        name: "Sam",
        role: "SLP",
        phone: "555-0191",
        preferredMethod: "text",
        primary: true,
      },
    ],
    lastContacted: "2026-06-01",
    lastVisited: "2026-04-28",
    sameDayFriendly: "sometimes",
    typicalVolume: "low",
    notes: "Worth checking when the route already pushes southwest.",
  },
  {
    id: "park-manor-south",
    name: "Park Manor South",
    address: "11902 Resource Pkwy, Houston, TX",
    city: "Southwest Houston",
    lat: 29.6358,
    lng: -95.5322,
    facilityType: "SNF",
    groupTag: "Park Manor",
    contacts: [
      {
        id: "c-south-heather",
        name: "Heather",
        role: "SLP",
        phone: "555-0135",
        preferredMethod: "text",
        primary: true,
      },
    ],
    lastContacted: "2026-05-12",
    lastVisited: "2026-04-25",
    sameDayFriendly: "yes",
    typicalVolume: "medium",
    notes: "Same network as Westchase but only useful when the route is already south.",
  },
  {
    id: "park-manor-cyfair",
    name: "Park Manor CyFair",
    address: "11001 Crescent Moon Dr, Houston, TX",
    city: "CyFair",
    lat: 29.9296,
    lng: -95.6211,
    facilityType: "SNF",
    groupTag: "Park Manor",
    contacts: [
      {
        id: "c-cyfair-dawn",
        name: "Dawn",
        role: "SLP",
        phone: "555-0177",
        preferredMethod: "call",
        primary: true,
      },
    ],
    lastContacted: "2026-06-02",
    lastVisited: "2026-04-13",
    sameDayFriendly: "yes",
    typicalVolume: "high",
    notes: "Same network, but usually a poor fit for inner-west routes.",
  },
  {
    id: "park-manor-tomball",
    name: "Park Manor Tomball",
    address: "250 School St, Tomball, TX",
    city: "Tomball",
    lat: 30.0987,
    lng: -95.6161,
    facilityType: "SNF",
    groupTag: "Park Manor",
    contacts: [
      {
        id: "c-tomball-lori",
        name: "Lori",
        role: "SLP",
        phone: "555-0156",
        preferredMethod: "text",
        primary: true,
      },
    ],
    lastContacted: "2026-04-30",
    lastVisited: "2026-03-22",
    sameDayFriendly: "sometimes",
    typicalVolume: "high",
    notes: "Same network, but usually not worth it unless the whole route is north.",
  },
  {
    id: "houston-transitional",
    name: "Houston Transitional Care",
    address: "8550 Memorial Dr, Houston, TX",
    city: "Memorial",
    lat: 29.7795,
    lng: -95.4921,
    facilityType: "LTACH",
    groupTag: "Houston Transitional",
    contacts: [
      {
        id: "c-transitional-paige",
        name: "Paige",
        role: "SLP",
        phone: "555-0181",
        preferredMethod: "email",
        primary: true,
      },
    ],
    lastContacted: "2026-06-25",
    lastVisited: "2026-05-29",
    sameDayFriendly: "no",
    typicalVolume: "low",
    notes: "Contact recently; avoid repeat asks unless already scheduled.",
  },
  {
    id: "bellaire-rehab",
    name: "Bellaire Rehab",
    address: "6300 Chimney Rock Rd, Houston, TX",
    city: "Bellaire",
    lat: 29.7114,
    lng: -95.4768,
    facilityType: "SNF",
    groupTag: "Independent",
    contacts: [
      {
        id: "c-bellaire-jen",
        name: "Jen",
        role: "SLP",
        phone: "555-0139",
        preferredMethod: "text",
        primary: true,
      },
    ],
    lastContacted: "2026-05-29",
    lastVisited: "2026-05-02",
    sameDayFriendly: "yes",
    typicalVolume: "medium",
    notes: "Good add-on if route crosses Bellaire before lunch.",
  },
  {
    id: "sugar-land-post-acute",
    name: "Sugar Land Post Acute",
    address: "1600 Lexington Blvd, Sugar Land, TX",
    city: "Sugar Land",
    lat: 29.6035,
    lng: -95.6348,
    facilityType: "SNF",
    groupTag: "Post Acute Partners",
    contacts: [
      {
        id: "c-sugarland-tia",
        name: "Tia",
        role: "SLP",
        phone: "555-0167",
        preferredMethod: "text",
        primary: true,
      },
    ],
    lastContacted: "2026-06-04",
    lastVisited: "2026-04-18",
    sameDayFriendly: "sometimes",
    typicalVolume: "medium",
    notes: "Usually a route-end option, not a middle-of-day detour.",
  },
  {
    id: "west-houston-ltach",
    name: "West Houston LTACH",
    address: "12141 Richmond Ave, Houston, TX",
    city: "Westchase",
    lat: 29.7302,
    lng: -95.6009,
    facilityType: "LTACH",
    groupTag: "West Houston",
    contacts: [],
    lastVisited: "2026-04-01",
    sameDayFriendly: "unknown",
    typicalVolume: "unknown",
    notes: "No reliable SLP contact yet. Good target to capture a contact on next visit.",
  },
  {
    id: "inactive-northwest",
    name: "Northwest Care Center",
    address: "14100 Northwest Fwy, Houston, TX",
    city: "Jersey Village",
    lat: 29.8804,
    lng: -95.5475,
    facilityType: "SNF",
    groupTag: "Independent",
    contacts: [
      {
        id: "c-nw-care",
        name: "Front Desk",
        role: "Main line",
        phone: "555-0111",
        preferredMethod: "call",
        primary: true,
      },
    ],
    sameDayFriendly: "no",
    typicalVolume: "low",
    notes: "Asked not to receive same-day add-on calls.",
    doNotContact: true,
  },
];

export const initialRouteStops: RouteStop[] = [
  {
    id: "stop-1",
    facilityId: "memorial-snf",
    order: 1,
    appointmentTime: "8:30 AM",
    studyCount: 2,
    status: "confirmed",
  },
  {
    id: "stop-2",
    facilityId: "park-manor-westchase",
    order: 2,
    appointmentTime: "10:15 AM",
    studyCount: 1,
    status: "confirmed",
  },
  {
    id: "stop-3",
    facilityId: "lakeside-rehab",
    order: 3,
    appointmentTime: "1:00 PM",
    studyCount: 2,
    status: "planned",
  },
];

export const initialOutreachLogs: OutreachLog[] = [
  {
    id: "log-1",
    facilityId: "park-manor-westchase",
    createdAt: "2026-06-21T08:05:00.000Z",
    method: "text",
    contactName: "Maria",
    status: "texted",
    notes: "Asked for same-day candidates before the Westchase stop.",
  },
  {
    id: "log-2",
    facilityId: "houston-transitional",
    createdAt: "2026-06-25T14:30:00.000Z",
    method: "call",
    contactName: "Paige",
    status: "no_patients_today",
    notes: "No appropriate add-ons that day.",
  },
];
